version: '3'

services:
    mysql:
      image : mysql/mysql-server:8.0.28
      container_name: mysql
      environment:
        TZ: Asia/Hong_Kong
        MYSQL_ROOT_PASSWORD: admin
      ports:
        - 3306:3306
      volumes:
        - ./datas/mysql/data:/var/lib/mysql
      #command to run when starting
      command:
        --default-authentication-plugin=mysql_native_password
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_general_ci
        --explicit_defaults_for_timestamp=true
        --lower_case_table_names=1
      privileged: true
      restart: always
      networks:
        - house-booking

    redis:
      image: redis:6.2.5
      container_name: redis
      ports:
        - 6379:6379
      # command to run when starting
      # set password forever
      command: "redis-server --requirepass admin --appendonly yes"
      privileged: true
      restart: always
      networks:


networks:
  house-booking:
    driver: bridge
    ipam: #ip address manager
      config:
        - subnet: 172.20.0.0/16