version: '3'

services:
  nginx:
    image: nginx:1.21.5
    container_name: nginx
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Hong_Kong
    ports:
      - 8888:8081
    volumes:
      - ./datas/nginx/log:/var/log/nginx
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - house-booking

networks:
  house-booking:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16