// Code generated by goctl. DO NOT EDIT.
package types

type HealthCheckReq struct {
}

type HealthCheckResp struct {
	Message string `json:"msg"`
}

type SignInReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInResp struct {
	Token       string `json:"token"`
	ExpiredTime uint   `json:"expired_time"`
}

type SignUpReq struct {
	Email    string `json:"email"`
	Name     string `json:"name""`
	Password string `json:"password"`
}

type SignUpResp struct {
	Token       string `json:"token"`
	ExpiredTime uint   `json:"expired_time"`
}

type GetProfileReq struct {
}

type GetProfileResp struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
